### ISSUE TITLE
simple_connectivity.podspec is missing

### ISSUE THREAD

**Issue by hugovangalen** [Vanethos/simple_connectivity#1]
The build fails with an "Error running pod install", 
```
[!] No podspec found for `simple_connectivity` in `~/.pub-cache/git/simple_connectivity-3adb415739601a4e17c8b33d31267eef9c07d438/ios` 
```
I renamed the "connectivity.podspec" file then it failed with:
```
[!] The name of the given podspec `connectivity` doesn't match the expected one `simple_connectivity`
```

I manually updated the name in the file and then the compile succeeded.

**Comment by Vanethos** [comment]
Pushed a new update, can you see if it's working?

And thanks for the issue!

**Comment by hugovangalen** [comment]
In the repository, I do see an updated README.md, .gitignore and pubspec.yaml file, but "connectivity.podspec" is still 3 months old, so I am not sure that it's working?

**Comment by Vanethos** [comment]
The podspec used is the same used by Google, as this is a simple fork of the library.

The conflict was in the names: it was using `simple_connectivity` and looking for the pod `connectivity`, hence the problem
