### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by Albert-Jan** [Vanethos/simple_connectivity#10]
Are there any plans to add web support?

**Comment by Vanethos** [comment]
Since connectivity now has support for web, I think I can try it, yes 🤔

**Comment by Albert-Jan** [comment]
I just looked into it, apparently, the _connectivity_ package moved the `NSLocationWhenInUseUsageDescription` requirement to a different package starting from version 2.0 back in October. So it deprecates this package's solution I guess. Thanks a lot for the efforts you've made  🙌
