### ISSUE TITLE
ITMS-90683: Missing Purpose String in Info.plist

### ISSUE THREAD

**Issue by volgin** [Vanethos/simple_connectivity#2]
After replacing "connectivity" plugin with simple_connectivity, I still get these warnings from Apple. If I remove simple_connectivity, the warnings go away (i.e. no other plugin causes them).

Are there some files in the iOs folder that need to be updated/recreated to make this issue go away? I understand that this was the only purpose of this fork.

**Comment by Vanethos** [comment]
Please try again with `0.1.0` published now in pubdev https://pub.dev/packages/simple_connectivity
