### ISSUE TITLE
App Store shows warning that the app is using location

### ISSUE THREAD

**Issue by finpro-svn** [Vanethos/simple_connectivity#3]
I need a way to check whether there is wifi or data connection. I was using the connectivity plugin for Flutter, however the App Store returned a warning that the plugin was using location services. I switched the connectivity plugin for simple_connectivity however the App Store still says that the app is using location services and I need to update info.plist with NSLocationAlwaysUsageDescription and NSLocationWhenInUseUsageDescription.

**Comment by Vanethos** [comment]
Will check on this asap

**Comment by finpro-svn** [comment]
I managed to prevent the App Store from flagging my app for using the location services by changing the FLTConnectivityLocationHandler.m file as detailed below. Please note that my knowledge of Objective C is very bad, but the changes seem to work for me.

`// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#import "FLTConnectivityLocationHandler.h"

@interface FLTConnectivityLocationHandler () <CLLocationManagerDelegate>

@property(copy, nonatomic) FLTConnectivityLocationCompletion completion;
//@property(strong, nonatomic) CLLocationManager *locationManager;

@end

@implementation FLTConnectivityLocationHandler

+ (CLAuthorizationStatus)locationAuthorizationStatus {
  //changed in order to avoid app store flaging app for use of location
  //return CLLocationManager.authorizationStatus;
  return kCLAuthorizationStatusDenied;
}

- (void)requestLocationAuthorization:(BOOL)always
                          completion:(FLTConnectivityLocationCompletion)completionHandler {
  //changed in order to avoid app store flaging app for use of location
  //CLAuthorizationStatus status = CLLocationManager.authorizationStatus;
  CLAuthorizationStatus status = kCLAuthorizationStatusDenied;

  if (status != kCLAuthorizationStatusAuthorizedWhenInUse && always) {
    completionHandler(kCLAuthorizationStatusDenied);
    return;
  } else if (status != kCLAuthorizationStatusNotDetermined) {
    completionHandler(status);
    return;
  }

  if (self.completion) {
    // If a request is still in process, immediately return.
    completionHandler(kCLAuthorizationStatusNotDetermined);
    return;
  }

  self.completion = completionHandler;
  /*self.locationManager = [CLLocationManager new];
  self.locationManager.delegate = self;
  if (always) {
    [self.locationManager requestAlwaysAuthorization];
  } else {
    [self.locationManager requestWhenInUseAuthorization];
  }*/
}
/*
- (void)locationManager:(CLLocationManager *)manager
    didChangeAuthorizationStatus:(CLAuthorizationStatus)status {
  if (status == kCLAuthorizationStatusNotDetermined) {
    return;
  }
  if (self.completion) {
    self.completion(status);
    self.completion = nil;
  }
}*/

@end`

**Comment by Vanethos** [comment]
Should work with `0.1.0` published now in pubdev https://pub.dev/packages/simple_connectivity
